### ISSUE TITLE
Word document converts the image,in Linux system Chinese garbled.  very urgent

### ISSUE THREAD

**Issue by pang691** [aspose-words/Aspose.Words-for-Java#60] opened 2019-11-13 01:34 UTC
When the Word document converts the image, the Chinese in the Windows system image will not be garbled, but it will be garbled when it is deployed to the Linux server and converted into a picture. How to solve it? The things on the Linux server cannot be moved. thanks very much

**Comment by AlexNosk** [comment] 2019-11-14 07:24
@pang691 Thank you for your request. Could you please attach the problematic document for testing? We will check and provide you more information. You can post here or in our [support forum](https://forum.aspose.com/c/words) (the main place for support).

**Comment by pang691** [comment] 2019-11-15 01:18
[test001.docx](https://github.com/aspose-words/Aspose.Words-for-Java/files/3849375/test001.docx)
This is the original document
![image](https://user-images.githubusercontent.com/51735160/68909166-6afaf600-0788-11ea-8f0d-8ff1c440101a.png)
This is a picture converted to a Linux server.
There is only a default font on the server, and other fonts are not allowed to be installed. How to solve this problem?
Thanks!!!

**Comment by AlexNosk** [comment] 2019-11-15 12:34
@pang691 Unfortunately without fonts documents cannot be properly rendered to images or any other fixed page formats (PDF, XPS etc). Also absence of fonts might cause problems upon updating fields, which results depend on page layout. 
To work the problem around it is not required to install fonts on the server. You can simply put the required fonts into a folder within your application and set this folder as font source in [FontSettings](https://apireference.aspose.com/java/words/com.aspose.words/FontSettings). Hope this helps.

**Comment by AlexNosk** [comment] 2019-11-18 12:48
@pang691 Was the above reply helpful for you? Can we close the issue?

**Comment by pang691** [comment] 2019-11-22 01:36
Sorry, I only see it now, I try the method you said, I will reply to you once I have the result, thank you very much.

**Comment by pang691** [comment] 2019-11-22 10:31
I put the font in the application directory, get the relative path of the font, and then use FontSettings.setFontsFolder (), deployed to the Linux server can not find the font under this folder, this is how, FontSettings.setFontsFolder (） Is the parameter an absolute path?

**Comment by AlexNosk** [comment] 2019-11-22 11:16
@pang691 setFontsFolder should accept both relative and absolute paths. But you can try specifying absolute path to make sure the path is correct. Use something like this to convert relative path to absolute
`String absolutePath = FileSystems.getDefault().getPath(mayBeRelativePath).normalize().toAbsolutePath().toString();`

**Comment by pang691** [comment] 2019-11-25 00:54
I use a relative path to deploy to a Linux server or a small square garbled. What is going on? Is there any other way?

**Comment by pang691** [comment] 2019-11-25 00:55
I use a relative path to deploy to a Linux server is also a small square garbled, how is this going? Is there any other way?

**Comment by AlexNosk** [comment] 2019-11-25 08:21
@pang691 Could you please create a simple document that allows to reproduce the problem and attach it here? Also let me know what Linux distribution you use. I will check the issue on my side and let you know my findings.

**Comment by pang691** [comment] 2019-11-25 14:23
I am reading a docx document from the server and then converting it to a picture. Later I will paste the code of how I convert the image and the code I use to set the font with a relative path. The garbled code will appear in the windows system. But deploying it to a Linux server is Chinese garbled (that is, posted above), which has blocked me for a long time, hoping to give a good implementation. Thank you

**Comment by pang691** [comment] 2019-11-25 14:26
I am reading a docx document from the server and then converting it to a picture. Later I will paste the code of how I convert the image and the code I use to set the font with a relative path. I will not get garbled under windows system. However, if it is garbled on the Linux server (that is, posted above), this has hindered me for a long time, hoping to give a good implementation. Thanks

**Comment by pang691** [comment] 2019-11-26 03:18
I tested in a Java environment
my generated output picture
![中文乱码](https://user-images.githubusercontent.com/51735160/69596699-72e74f80-103e-11ea-958d-ac2b1f07a072.jpg)

my Word document
[中文乱码.zip](https://github.com/aspose-words/Aspose.Words-for-Java/files/3889894/default.zip)


I tried the code but it didn’t work
LoadOptions opt = new LoadOptions();
opt.setEncoding(Encoding.CHARSET_GB2312);
Document doc = new Document(inputstream,opt);
FontInfoCollection fonts = doc.getFontInfos();
fonts.setEnbedTrueTypeFonts(true);
fonts.setEmbedSystemFonts(false);
fonts.setSaveSusetFonts(false);
FontSettings fontsettings = FontSettings.getDefaultInstance();
fontsettings.setFontsFolder("/static/font/chinese/",true);
doc.setFontSettings(fongsettings);
doc.save(outputstream,SaveFormat.PNG);

thanks

**Comment by pang691** [comment] 2019-11-26 08:46
![image](https://user-images.githubusercontent.com/51735160/69612381-87d9d800-106a-11ea-9c87-25433fa4cfbc.png)
This is the structure of my project. I put the font under the red box folder and use setFontSetting to specify the relative path of the folder, but it didn't work. What is going on?
![image](https://user-images.githubusercontent.com/51735160/69612583-f3bc4080-106a-11ea-9c9e-7a669f750f82.png)
I am used Linux distribution

**Comment by AlexNosk** [comment] 2019-11-27 13:22
@pang691 Thank you for additional information. I will check the scenario on my side and get back to you with results.

**Comment by pang691** [comment] 2019-12-03 01:26
Hello, did you get garbled characters there? Solve it?  thanks

**Comment by AlexNosk** [comment] 2019-12-03 12:32
@pang691 Hello, excuse me for a late response. I managed to reproduce garbled characters. The problem occurs because Aspose.Words cannot find the fonts. You can easily check this by saving the output document to PDF and checking its properties - the PDF will contain only Fonwood font, which is the last resort font.
I managed to make it work by using absolute path for fonts folder. I create a simple application, packed it in JAR, place fonts folder next to the JAR file and use this code to specify fonts folder:

`
// get folder where running jar os located
String jarFolder = new File(Main.class.getProtectionDomain().getCodeSource().getLocation().toURI()).getParentFile().getPath();
fontsettings.setFontsFolder(jarFolder+"/fonts/chinese",true);
`
Hope this helps.

**Comment by pang691** [comment] 2019-12-13 01:25
Thank you very much, I have solved this problem with relative paths, thank you for your help

**Closed as completed** 2019-12-13 08:03 UTC
